### ISSUE TITLE
Request:  Add new day detection under events.cs

### ISSUE THREAD

**Issue by cantorsdust** [Zoryn4163/SMAPI#12]
See http://community.playstarbound.com/threads/freezeinside-mod-freeze-time-while-indoors-like-harvest-moon.107724/

Essentially, I can detect when a player is inside and freeze time.  But while the player sleeps inside, time stays frozen and does not reset to 0600.  If I could detect when the day changes, I could reset the time.

Thank you!

**Comment by Zoryn4163** [comment]
5a33d4c7f2f136fdd821ab46e2a44325e4559627 should add these features. Use SMAPI 0.35+. Tell me if there are any issues
