### ISSUE TITLE
Crash when there is no ErrorLogs folder in %appdata%\Stardew Valley

### ISSUE THREAD

**Issue by cantorsdust** [Zoryn4163/SMAPI#8]
Reproducible crash if there is no error logs folder in %appdata%\Stardew Valley.  See http://community.playstarbound.com/threads/stardew-modding-api.107021/page-5#post-2796632

Double checked myself.  Reported solved if such folder is created.

**Comment by Zoryn4163** [comment]
Should auto-generate in current version
