### ISSUE TITLE
Poorly structured

### ISSUE THREAD

**Issue by mdbell** [Zoryn4163/SMAPI#9]
This "api" isn't structured at all, it seems like nothing was planned out at all. You're directly interacting with/inheriting classes from the base game instead of wrapping them. What will happen to any mods if the base game change some names internally?

Like this is a good effort, but your code base is a mess.

**Comment by Zoryn4163** [comment]
Well I'm sorry but this is all I know how to do. It's working, so that works for me.

**Comment by mdbell** [comment]
I didn't mean to illicit such a response like that from you, it's just that if you keep working on it in it's current state, your codebase will become not only messy, but nearly impossible to maintain (I am talking from experience here). My best advice would be to step away and actually model your code out.

And usually when a game updates and breaks a mod, it's not because of a field or method being renamed, but from it being changed on a functional level.

**Comment by Zoryn4163** [comment]
Well I'm going to be honest, I don't know how I would go about doing that. I don't understand the game on a fundamental level and I don't know of any other way to do what I'm doing. My chief concern currently is to get modding to work - if in the long run I have to completely redo my codebase I will. 

And I apologize about the response, I am very stressed out over some things irl currently.
